# Generated by Django 3.2.5 on 2022-05-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_target', models.BooleanField(blank=True, default=False)),
                ('hits', models.PositiveIntegerField(blank=True, null=True)),
                ('fired', models.ImageField(blank=True, null=True, upload_to='')),
                ('detected', models.ImageField(blank=True, null=True, upload_to='')),
                ('detected_hits', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firing.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Firer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('coy', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('fire', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firing.fire')),
                ('firer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firing.firer')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='target_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_1', to='firing.firer'),
        ),
    ]
