# Generated by Django 3.2.5 on 2022-05-24 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firing', '0003_firer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('firer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firing.firer')),
            ],
        ),
    ]
