# Generated by Django 3.2.5 on 2022-05-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firing', '0004_auto_20220524_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='cls',
            field=models.CharField(blank=True, choices=[('One', 'one'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five')], max_length=200, null=True),
        ),
    ]
