# Generated by Django 3.2.5 on 2022-06-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firing', '0005_weapon_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='zeroed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
